### ISSUE TITLE
[1.12] Error trying to Paste schematic

### ISSUE THREAD

**Issue by Morpheus1101** [HexoMod/WorldEditCUI-Forge-Edition-2#7]
Error log @ https://puu.sh/wMHVi/02fe32a484.txt

In game error pic @ https://puu.sh/wMHYg/83eb353593.png

**Comment by hexosse** [comment]
Sorry, but this is an error from WorldEdit not from WorldEdit CUI.

**Comment by Morpheus1101** [comment]
CUI edition is what i have loaded 

https://puu.sh/wN0tm/fbb29f64b1.png
https://puu.sh/wN0xO/95e2704d96.png

**Comment by hexosse** [comment]
Look at your logs, it say :

 [**WorldEdit**] An unexpected error while handling a WorldEdit command
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
at **party.lemons.anima**.content.block.BlockSolarCollector.func_149915_a(BlockSolarCollector.java:24)

So it comes from WorldEdit or PartyLemon.

But the problem is how can you use WorldEdit with forge 1.12 as there is no version yet for 1.12 ?

**Comment by Morpheus1101** [comment]
I installed it via the curse launcher

https://puu.sh/wN1q7/8f29b80f4d.png

**Comment by hexosse** [comment]
Don't misunderstand, this is **WorldEdit CUI** not **WorldEdit**

all your logs indicate that your error comes from com.sk89q.worldedit which is a **WorldEdit**
class, so you'd better open an issue on WorldEdit github page.

There's nothing I can do for you as WorldEdit is not my mod.
